name: Deploy Backend (Dev)
on: workflow_dispatch

jobs:
  test:
    uses: ./.github/workflows/test-backend.yml
  deploy:
    runs-on: ubuntu-latest
    needs: test

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
      DB_HOST: ${{ secrets.DB_DEV_HOST }}
      DB_NAME: ${{ secrets.DB_DEV_NAME }}
      DB_USERNAME: ${{ secrets.DB_DEV_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_DEV_PASSWORD }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

    steps:
      # checkout code
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # setup nodejs
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      # setup backend
      - run: npm ci
        working-directory: ./backend

      # deploy backend
      - run: npm run deploy:dev
        working-directory: ./backend
