name: Test Executor
on:
  - pull_request
  - workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      # setup nodejs and python
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Run Executor Tests
        working-directory: ./services/executor
        run: |
          npm ci
          pip install -r requirements.txt
          pytest